GET http://localhost:8080/user/order
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM4MzkwYmI3LWVlNDEtNDZmYi05ZDMyLTQ1MTRkNDcyNjFmMyIsImlzQWRtaW4iOnRydWUsInRva2VuIjoiY21GdVpHOXRMV3AzZEMxelpXTnlaWFF0YTJWNUxYTjFjR1Z5TFdWNGNHVnVjMmwyWlMxd2NtOD0iLCJpYXQiOjE3MzEzNDAxNDMsImV4cCI6MTczMTQyNjU0M30.HYljoHzBHumtqGj7Yg9Bk9467JMkT-_QF3y4IMSJUx0


###
GET http://localhost:8080/user/cart
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM4MzkwYmI3LWVlNDEtNDZmYi05ZDMyLTQ1MTRkNDcyNjFmMyIsImlzQWRtaW4iOnRydWUsInRva2VuIjoiY21GdVpHOXRMV3AzZEMxelpXTnlaWFF0YTJWNUxYTjFjR1Z5TFdWNGNHVnVjMmwyWlMxd2NtOD0iLCJpYXQiOjE3MzEzNDAxNDMsImV4cCI6MTczMTQyNjU0M30.HYljoHzBHumtqGj7Yg9Bk9467JMkT-_QF3y4IMSJUx0